challenge/urls.py
from django.urls import path, include

from rest_framework import routers

from . import views

router = routers.DefaultRouter()
router.register(r'tracking', views.TrackingViewSet)
router.register(r'checkpoint', views.CheckpointViewSet)


app_name = 'challenge'
urlpatterns = [
    path('', views.get_email, name='email'),
    path('orders/', views.TrackingView.as_view(), name='index'),
    path('tracking/<int:tracking_number>/', views.DetailView.as_view(), name='detail'),
    path('api/', include(router.urls)),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework'))
]

parcellab/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('challenge/', include('challenge.urls')),
]

challenge/models.py
from django.db import models


# These models correspond to the CSV files.
# column names are taken directly from the CSV.
# Depending on company convention, these might also be underscored.

class Tracking(models.Model):
    orderNo = models.CharField(max_length=200)
    tracking_number = models.IntegerField(unique=True, primary_key=True)
    courier = models.CharField(max_length=200)
    street = models.CharField(max_length=200)
    zip_code = models.CharField(max_length=200)
    city = models.CharField(max_length=200)
    destination_country_iso3 = models.CharField(max_length=3)
    email = models.CharField(max_length=200)
    articleNo = models.CharField(max_length=200)
    articleImageUrl = models.CharField(max_length=200)
    quantity = models.CharField(max_length=200)
    product_name = models.CharField(max_length=200)

    def __str__(self):
        return self.orderNo


class Checkpoint(models.Model):
    # this should probably be converted to an int key, eventually.
    tracking_number = models.ForeignKey(
        Tracking, on_delete=models.CASCADE, to_field='tracking_number')
    # should be changed to
    # tracking_number = models.CharField(max_length=200)
    location = models.CharField(max_length=200)
    timestamp = models.DateTimeField('date recorded')
    status = models.CharField(max_length=200)
    status_text = models.CharField(max_length=200)
    status_details = models.CharField(max_length=200)

    def __str__(self):
        return str(self.timestamp) + self.status_text

challenge/forms.py
from django import forms


class EmailForm(forms.Form):
    email = forms.CharField(label='Your email', max_length=100)

challenge/views.py
from django.views import generic
from django.http import HttpResponseRedirect
from django.shortcuts import render


from rest_framework import viewsets, permissions

from .models import Tracking, Checkpoint
from .forms import EmailForm
from challenge.serializers import CheckpointSerializer, TrackingSerializer


def get_email(request):
    """
    This is an autogenerated form for collecting user emails
    """
    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        form = EmailForm(request.POST)
        # check whether it's valid:
        if form.is_valid():
            # process the data in form.cleaned_data as required
            # redirect to a new URL:
            return HttpResponseRedirect('/thanks/')

    # if a GET (or any other method) create a blank form
    else:
        form = EmailForm()

    return render(request, 'challenge/email.html', {'form': form})


class TrackingView(generic.ListView):
    """
    A view for returning tracking instances that match the provided email address.
    """
    template_name = 'challenge/tracking.html'
    context_object_name = 'tracking_number_list'

    def get_queryset(self):
        """Return the tracking numbers with the appropriate email"""
        return Tracking.objects.filter(email=self.request.GET['email'])


class DetailView(generic.ListView):
    """
    A view for displaying checkpoints corresponding to a particular tracking object
    """
    template_name = 'challenge/checkpoints.html'
    context_object_name = 'checkpoint_list'

    def get_queryset(self):
        return Checkpoint.objects.filter(tracking_number=self.kwargs['tracking_number'])


class CheckpointViewSet(viewsets.ModelViewSet):
    """
    API endpoint that allows checkpoints to be viewed or edited.
    """
    queryset = Checkpoint.objects.all()
    serializer_class = CheckpointSerializer
    permission_classes = [permissions.IsAuthenticated]


class TrackingViewSet(viewsets.ModelViewSet):
    """
    API endpoint that allows tracking objects to be viewed or edited.
    """
    queryset = Tracking.objects.all()
    serializer_class = TrackingSerializer
    permission_classes = [permissions.IsAuthenticated]

challenge/templates/challenge/checkpoints.html
<!-- {% debug %} -->

<h1><a href="{% url 'challenge:index' %} "> Go Back to Orders </a></h1>
<h1>Checkpoints</h1>
{% if checkpoint_list %}
    {% for checkpoint in checkpoint_list %}
    <ul>
        <h3>{{ checkpoint.status_text }}</h3>
        <ul>
            <li>tracking_number: {{ checkpoint.tracking_number }}</li>
            <li>location: {{ checkpoint.location }}</li>
            <li>timestamp: {{ checkpoint.timestamp }}</li>
            <li>status: {{ checkpoint.status }}</li>
            <li>status_text: {{ checkpoint.status_text }}</li>
            <li>status_details: {{ checkpoint.status_details }}</li>
        </ul>
    </ul>
    {% endfor %}
{% else %}
    <p>No checkpoints are available.</p>
{% endif %}

challenge/templates/challenge/email.html
<h2>Track Your Orders</h2>
<form action="orders/" method="get">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Submit">
</form>

challenge/templates/challenge/tracking.html
<h1>You are Tracking the Following Orders:</h1>
{% if tracking_number_list %}
    <ul>
    {% for tracking in tracking_number_list %}
    	<li><h4>See Checkpoints for <a href="{% url 'challenge:detail' tracking.tracking_number %}">{{ tracking.orderNo }}</a></h4>
            <ul>
                <li>tracking_number: {{ tracking.street }}</li>
                <li>street: {{ tracking.street }}</li>
                <li>zip_code: {{ tracking.zip_code }}</li>
                <li>city: {{ tracking.city }}</li>
                <li>destination_country_iso3: {{ tracking.destinati_country_iso3on }}</li>
                <li>email: {{ tracking.email }}</li>
                <li>articleNo: {{ tracking.articleNo }}</li>
                <!-- There should be an image url included in the future
                    <li>ArticleImageUrl: {{ tracking.courier ArticleImageUrl}</li> -->
                <li>quantity: {{ tracking.quantity }}</li>
                <li>product_name: {{ tracking.product_name}}</li>
            </ul>
        </li>

    {% endfor %}
    </ul>
{% else %}
    <p>No orders are available.</p>
{% endif %}